import Foundation

/// 雅思听力分析报告：
/// 1. ASR 转录总录音（上下文全文）和每个打标绿段；
/// 2. 在全文里模糊定位每个绿段的文字，加粗标注并在旁边放音频文件链接；
/// 3. 落盘 Markdown 到 reports/LC_xxx_听力分析.md（后续接飞书 CLI 上传）。
enum ReportGenerator {
    struct SegmentResult {
        let segment: ClipSegment
        let text: String
        var matched = false
    }

    static func generate(meta: ClipMetadata, store: ClipStore, asr: ASRService) async throws -> URL {
        let fullText = try await asr.transcribe(fileURL: store.fileURL(for: meta))
        var segmentResults: [SegmentResult] = []
        for segment in meta.segments ?? [] {
            let url = store.clipsDir.appendingPathComponent(segment.file)
            let text = try await asr.transcribe(fileURL: url)
            segmentResults.append(SegmentResult(segment: segment, text: text))
        }
        let markdown = buildMarkdown(meta: meta, fullText: fullText, segments: segmentResults)
        let reportURL = store.reportURL(for: meta.id)
        try markdown.write(to: reportURL, atomically: true, encoding: .utf8)
        return reportURL
    }

    // MARK: - Markdown

    static func buildMarkdown(
        meta: ClipMetadata,
        fullText: String,
        segments: [SegmentResult]
    ) -> String {
        var segments = segments
        let numbers = ["①", "②", "③", "④", "⑤", "⑥", "⑦", "⑧", "⑨", "⑩",
                       "⑪", "⑫", "⑬", "⑭", "⑮", "⑯", "⑰", "⑱", "⑲", "⑳"]
        func mark(_ i: Int) -> String { i < numbers.count ? numbers[i] : "(\(i + 1))" }

        // 在全文中定位每个绿段文字（忽略大小写/标点/空白的模糊匹配）。
        let annotatedFull = annotate(fullText: fullText, segments: &segments, mark: mark)

        var md = """
        # 听力训练分析 · \(meta.id)

        - 录制时间：\(meta.created_at)
        - 总时长：\(meta.duration_sec)s
        - 没听懂的片段：\(segments.count) 段
        - 总录音：[\(meta.audio_file)](../clips/\(meta.audio_file))

        ## 全文转录（上下文）

        \(annotatedFull.isEmpty ? "（ASR 未识别出内容）" : annotatedFull)

        """

        if !segments.isEmpty {
            md += "\n## 没听懂的片段\n"
            for (i, result) in segments.enumerated() {
                let seg = result.segment
                md += """

                ### \(mark(i)) \(seg.start_sec)s – \(seg.end_sec)s（\(seg.duration_sec)s）

                - 🎧 音频：[\(seg.file)](../clips/\(seg.file))
                - 转录：\(result.text.isEmpty ? "（ASR 未识别出内容）" : result.text)
                - 全文定位：\(result.matched ? "已在全文中加粗标注 \(mark(i))" : "未能自动匹配，请结合时间区间人工定位")
                - 错因笔记：

                """
            }
        }

        md += """

        ---
        *Generated by Listening Clip Pipe · ASR: \(ASRService.model)*
        """
        return md
    }

    /// 把每个绿段的转录文字在全文里定位并标注：
    /// `**①【 …匹配文字… 】** [🎧](../clips/xxx.wav)`。
    /// 匹配方式：双方都归一化成「小写字母+数字」序列后做子串搜索，再映射回原文区间。
    static func annotate(
        fullText: String,
        segments: inout [SegmentResult],
        mark: (Int) -> String
    ) -> String {
        let (fullChars, fullMap) = normalize(fullText)
        var insertions: [(range: Range<String.Index>, index: Int)] = []

        for (i, result) in segments.enumerated() {
            let (segChars, _) = normalize(result.text)
            // 太短的匹配没有意义（比如只识别出一两个字符）
            guard segChars.count >= 3 else { continue }
            guard let offset = find(segChars, in: fullChars) else { continue }
            let startIndex = fullMap[offset]
            let lastIndex = fullMap[offset + segChars.count - 1]
            let endIndex = fullText.index(after: lastIndex)
            let range = startIndex..<endIndex
            // 跳过与已有标注重叠的区间
            if insertions.contains(where: { $0.range.overlaps(range) }) { continue }
            insertions.append((range, i))
            segments[i].matched = true
        }

        var annotated = fullText
        for insertion in insertions.sorted(by: { $0.range.lowerBound > $1.range.lowerBound }) {
            let i = insertion.index
            let audioLink = " [🎧\(mark(i))](../clips/\(segments[i].segment.file))"
            annotated.insert(
                contentsOf: "】**\(audioLink)",
                at: insertion.range.upperBound
            )
            annotated.insert(
                contentsOf: "**\(mark(i))【",
                at: insertion.range.lowerBound
            )
        }
        return annotated
    }

    /// 归一化：只保留字母和数字（小写），并记录每个归一化字符对应的原文 String.Index。
    static func normalize(_ text: String) -> ([Character], [String.Index]) {
        var chars: [Character] = []
        var map: [String.Index] = []
        var i = text.startIndex
        while i < text.endIndex {
            let c = text[i]
            if c.isLetter || c.isNumber {
                for lower in c.lowercased() {
                    chars.append(lower)
                    map.append(i)
                }
            }
            i = text.index(after: i)
        }
        return (chars, map)
    }

    /// 朴素子串搜索（文本量小，性能足够）。
    static func find(_ needle: [Character], in haystack: [Character]) -> Int? {
        guard !needle.isEmpty, haystack.count >= needle.count else { return nil }
        for start in 0...(haystack.count - needle.count) {
            var matched = true
            for j in 0..<needle.count where haystack[start + j] != needle[j] {
                matched = false
                break
            }
            if matched { return start }
        }
        return nil
    }
}
